version: '3.8'
services:
  api:
    build: .
    container_name: app_api_gateway
    restart: always
    env_file:
      - docker.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - cache

  postgres:
    image: postgres:14.1-alpine
    container_name: db_api_gateway
    restart: always
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    container_name: cache_api_gateway
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  postgres:
    driver: local
  cache:
    driver: local

