---
name: Deploy Projeto "voce_api_gateway"
on:
  push:
    branches:
      - main
    paths:
      - devops/**
  pull_request:
    paths:
      - devops/**

jobs:
  remote_command_job:
    runs-on: ubuntu-latest
    name: SSH Remote command
    steps:
      - name: SSH Deployer
        uses: msatbsx/ssh-and-run-your-script-on-remote-host@v0.1.1 # replace with current tag, avoid using main or latest
#    steps:
#      - name: Conectando ao server AWS
#        uses: kevin-leptons/ssh_action@v1
        with:
          user: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.REMOTE_KEY }}

      - name: Executando script
        run: chmod +x /var/www/html/deploy/devops_voce_api_gateway.sh && ./var/www/html/deploy/devops_voce_api_gateway.sh
